- name: Download RHEL ISO
  hosts: localhost
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Include package downloader role
      ansible.builtin.include_role:
        name: package-downloader
      vars:
        rh_product_filename: rhel.iso
        rh_product_checksum: "{{ checksum.rhel9 }}"
        rh_api_offline_token: "{{ offline_token }}"
      when: offline_token is defined and offline_token != ""

- name: This play provisions VMs for AAP2 demos
  hosts: localhost
  become: true
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Provision libvirt VM using role
      ansible.builtin.include_role:
        name: host-provisioner
      vars:
        host_modules: "{{ modules }}"
        host_domain: "{{ domain }}"
        host_network_cidr: "{{ network_cidr }}"

    - name: Ensure to clean known_hosts
      ansible.builtin.known_hosts:
        host: "{{ item.hostname }}.{{ domain }}"
        path: ~/.ssh/known_hosts
        state: absent
      loop: "{{ modules }}"
      become: false

- name: Check connection to servers
  hosts: controller,hub,servicecatalog,sso
  gather_facts: false
  tasks:
    - name: Waiting for installation to end, it can take time!
      ansible.builtin.wait_for_connection:
        timeout: 1800
        sleep: 120

    - name: Ping host to check status
      ansible.builtin.ping:

    - name: Setup is ready
      ansible.builtin.debug:
        msg: "Setup completed, now you can proceed with post install steps"
