packages:
  - python3-lxml
  - python3-netaddr
  - python3-libvirt
  - python3-pip
  - libvirt-devel
  - libvirt
  - qemu-kvm
  - virt-install
  - virt-manager
modules:
  - module: 01_controller_instance
    instance: controller
    hostname: controller
  - module: 02_hub_instance
    instance: automation-hub
    hostname: hub
domain: aapdemo.labs
checksum:
  aap2: 39c5f84421585fe0171fc0532d3507d195fc32bf5b74e53bfd4e9bcca7a0fcd0
  rhel9: c6942e3ed65947ed48c30589d9c1a752e96c5b94ee8de1923331449fee162cc1

